openapi: 3.0.0
info:
  title: Stream Dashboard Ingestion API
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8080
paths:
  /write_stream_session/{stream_key}:
    post:
      summary: Creates a new stream session, and store to database
      description: ''
      operationId: ''
      parameters:
        - in: path
          name: stream_key
          schema:
            type: integer
          required: true
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Session"
      responses:
        default:
          description: Default error sample response
  /write_datapoints/{stream_key}:
    post:
      summary: Creates a set of data points, and store to database
      description: ''
      operationId: ''
      parameters:
        - in: path
          name: stream_key
          schema:
            type: integer
          required: true
      requestBody:
        content:
          "application/json":
            schema:
              type: array
              items:
                $ref: "#/components/schemas/DataPoint"
      responses:
        default:
          description: Default error sample response
  /write_datapoint/{stream_key}:
    post:
      summary: Creates a data point and store to database.
      description: ''
      operationId: ''
      parameters:
        - in: path
          name: stream_key
          schema:
            type: integer
          required: true
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/DataPoint"
      responses:
        default:
          description: Default error sample response
  /point_bitrate_heatmap:
    get:
      summary: Retrieves the signal heatmap in GeoJSON format (as points)
      description: ""
      operationId: ""
      responses:
        default:
          description: Default error sample response
  /polygon_bitrate_heatmap:
    get:
      summary: Retrieves the signam heatmap in GeoJSON format (as polygons)
      description: ""
      operationId: ""
      responses:
        default:
          description: Default error sample response
components:
  schemas:
    Session:
      type: object
      properties:
        streamId:
          type: string
        videoCodec:
          type: string
        audioCodec:
          type: string
        videoResolution:
          type: string
        server:
          type: string
        duration:
          type: integer
          format: int32
        modemCount:
          type: integer
          format: int32
        unstableEvents:
          type: integer
          format: int32
        startDate:
          type: integer
          format: int64
          description: Epoch Unix Timestamp
        endDate:
          type: integer
          format: int64
          description: Epoch Unix Timestamp
    DataPoint:
      type: object
      properties:
        streamId:
          type: string
        modems:
          type: array
          items: 
            $ref: "#/components/schemas/Modem"
        latitude:
          type: integer
          format: int32
        longitude:
          type: integer
          format: int32
        bitrate:
          type: integer
          format: int32
        audioBitrate:
          type: integer
          format: int32
        fps:
          type: integer
          format: int32
        ping:
          type: integer
          format: int32
        streamTitle:
          type: string
        startDate:
          type: integer
          format: int64
          description: Epoch Unix Timestamp
        endDate:
          type: integer
          format: int64
          description: Epoch Unix Timestamp
    Modem:
      type: object
      properties:
        name:
          type: string
        temperature:
          type: integer
          format: int32
        upstreamBandwidth:
          type: integer
          format: int32
        downstreamBandwidth:
          type: integer
          format: int32
        type:
          type: string
