name: Docker Server CI

on:
  pull_request:
    branches: [ main ]
    paths: [ "server/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./server --file ./server/Dockerfile
